name: linux-builds

on:
  push:

env:
  OWNER: ${{ github.repository_owner }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:

  linux:
    runs-on: ubuntu-latest

    timeout-minutes: 30

    strategy:
      matrix:
        file: [drone-server, verdaccio, node, gitlab-ce, gitlab-runner, renovate, github-runner]

    env:
      FILE: ${{ matrix.file }}
      IMAGE: ghcr.io/${{ github.repository_owner }}/${{ matrix.file }}

    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2.4.0

      - name: docker-config
        uses: renovatebot/internal-tools@eb0c61ae004ee415774a12de5adb282ab06b7457 # renovate: tag=v1.10.0
        with:
          command: docker-config

      - name: Build the Docker image
        run: docker buildx bake --progress plain test

      - name: Test run
        run: docker-compose --file docker-compose.test.yml run sut
        working-directory: ./linux/${{ env.FILE }}

      - name: Log into registry
        if: github.ref == 'refs/heads/main'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Publish the Docker image
        if: github.ref == 'refs/heads/main'
        run: docker buildx bake build

      - name: Publish the Docker image tags
        if: github.ref == 'refs/heads/main'
        run: |
          if [ -f push.sh ]; then
            ./push.sh
          fi
        working-directory: ./linux/${{ env.FILE }}
