name: linux-builds

on:
  push:

env:
  OWNER: ${{ github.repository_owner }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:

  linux:
    runs-on: ubuntu-latest

    timeout-minutes: 30

    strategy:
      matrix:
        file: [drone-server, verdaccio, node, gitlab-ce, gitlab-runner, renovate, github-runner]

    env:
      FILE: ${{ matrix.file }}
      IMAGE: ghcr.io/${{ github.repository_owner }}/${{ matrix.file }}

    steps:
      - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748 # tag=v3.0.1

      - name: docker-config
        uses: renovatebot/internal-tools@ad4cae0e4b6549fb28b1be633d4901db9ffa53d2 # tag=v1.12.8
        with:
          command: docker-config

      - name: Build the Docker image
        run: docker buildx bake --progress plain test

      - name: Test run
        run: docker-compose --file docker-compose.test.yml run sut
        working-directory: ./linux/${{ env.FILE }}

      - name: Log into registry
        if: github.ref == 'refs/heads/main'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Publish the Docker image
        if: github.ref == 'refs/heads/main'
        run: docker buildx bake build

      - name: Publish the Docker image tags
        if: github.ref == 'refs/heads/main'
        run: |
          if [ -f push.sh ]; then
            ./push.sh
          fi
        working-directory: ./linux/${{ env.FILE }}
